### ISSUE TITLE
一直更新吗

### ISSUE THREAD

**Issue by pandaOreo** [wcz0/laravel-vben#1]

**Comment by wcz0** [comment]
不, 只是写个基础案例, 提供参考. 只更新bug, 可以考虑其他快速开发后台的框架, 例如slow-admin

**Comment by pandaOreo** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
